### ISSUE TITLE
Hope to add a .fbx export plugin for MeshLab  

### ISSUE THREAD

**Issue by wityhb** [cnr-isti-vclab/PyMeshLab#101]
Hi, I found that .fbx file import and export is asymmetric.  Now i want to export .fbx file by add an export plugin for MeshLab,  could you please give me some hints? And what should I pay attention to when dealing with uv and uv2 about .fbx? [https://github.com/cnr-isti-vclab/PyMeshLab/issues/98#issuecomment-824503589](url)Thanks!

**Comment by alemuntoni** [comment]
Hi, @thanks @wityhb. We know that some importer/exporter in meshlab/pymeshlab need a revision, and help is always appreciated :)
About uv and uv2, if I understood correctly, it means that there are two textures and a vertex could refer to one or another (but not both at the same time)?
Because the vcg mesh allows to store only one couple of u/v coordinates per vertex, and one couple of u/v coordinates per wedge (https://stackoverflow.com/questions/61724879/what-does-wedge-means-in-vcglib). Associated to these coordinates, there is an id that refers to the i-th texture saved in the texture list of the mesh.
