### ISSUE TITLE
Filter not selecting model

### ISSUE THREAD

**Issue by eduvillasr** [cnr-isti-vclab/PyMeshLab#135]
I am attempting to translate two models to the origin and then performing a boolean operation. Here is my code:

---
import pymeshlab

ms = pymeshlab.MeshSet()
ms.load_new_mesh("20mm_cube.stl")
ms.load_new_mesh("qrcode.stl")
ms.set_current_mesh(0)

ms.transform_rotate_to_fit_to_a_plane(toorigin=True)
ms.apply_filter('mesh_boolean_difference')
ms.save_current_mesh("pymeshlabtest.stl")

---

Here is the error:

---
PyMeshLabException: Failed to apply filter: transform_rotate_to_fit_to_a_plane
Details: Cannot compute rotation: there is no selection
---
I am thinking this is a beginner's solution but I could not find the answer in the documentation.

Thank you!

**Comment by alemuntoni** [comment]
As documentation of the filter `transform_rotate_to_fit_to_a_plane` says:

_Generate a matrix transformation that rotates the mesh so that **the selection** fits one of the main planes XY YZ ZX._

You don't have any component selected in the mesh with id 0, and therefore the filter cannot be applied,
If you try to make the exact same operation with the meshlab GUI, you get the same error.

I think that what you need to do is to use the filter [transform_translate_center_set_origin](https://pymeshlab.readthedocs.io/en/latest/filter_list.html#transform_translate_center_set_origin) to set its center into the origin, by calling:
```
ms.transform_translate_center_set_origin(traslmethod='Center on Layer BBox')
```

**Comment by eduvillasr** [comment]
*Thank you so much, that worked for me!*
