### ISSUE TITLE
Possible incompatibility when saving normals in ply file

### ISSUE THREAD

**Issue by sergiobdrl** [cnr-isti-vclab/PyMeshLab#145]
Hi

I'm making a mesh with positions and normals from numpy values and exporting as PLY. When I load the data into a Metashape project, in the console, I see that the normals are being computed, which is strange since the data already has normals. To debug this, I loaded a PLY exported with pymeshlab using Open3D. According to Open3D the pointcloud has no normals. However, when I load the PLY with pymeshlab, it seems the normals are there. Is it possible that there is some incompatibility between pymeshlab and some of these other libraries?
```
>>> fake_pos.shape
(1000, 3)
>>> fake_normals.shape
(1000, 3)
>>> mesh = pymeshlab.Mesh(vertex_matrix = fake_pos, v_normals_matrix = fake_normals)
>>> ms = pymeshlab.MeshSet()
>>> ms.add_mesh(mesh)
>>> ms.save_current_mesh("/workspace/garbage/normal_test/normal_test_save.ply")
>>> pc = o3d.io.read_point_cloud("/workspace/garbage/normal_test/normal_test_save.ply")
>>> pc.has_normals()
False
>>> ms_load = pymeshlab.MeshSet()
>>> ms_load.load_new_mesh("/workspace/garbage/normal_test/normal_test_save.ply")
>>> loaded_mesh = ms_load.current_mesh()
>>> normals = loaded_mesh.vertex_normal_matrix()
>>> normals.shape
(1000, 3)
```

**Comment by alemuntoni** [comment]
In pymeshlab, meshes always store normals internally. If they are not in the loaded file, they are computed after the file is loaded. That's why you will always get a non-empty matrix when calling the `vertex_normal_matrix` method.
I don't know if other libraries have the same behaviour.

When saving a ply mesh with `save_current_mesh`, the parameter `save_vertex_normal` is set to `False` by default (https://pymeshlab.readthedocs.io/en/latest/io_format_list.html), therefore normals are not saved into the file.
