### ISSUE TITLE
How to render process of PyMeshLab, such as QT

### ISSUE THREAD

**Issue by LeoXiaoNian** [cnr-isti-vclab/PyMeshLab#168]
Hello Sir, I want to try to use QT to render the process of PyMeshLab. How can I get data from PyMeshLab? For example, the data in the MeshSet class, Thank you in advance！

Or we must save it as an STL file and render it every time？

**Comment by alemuntoni** [comment]
There is no-way to do that using pymeshlab at the moment. See https://github.com/cnr-isti-vclab/PyMeshLab/issues/164

**Comment by LeoXiaoNian** [comment]
Can I render with pyglet or pyrender? thanks

**Comment by alemuntoni** [comment]
You can use the [methods of the mesh class](https://pymeshlab.readthedocs.io/en/latest/classes/mesh.html) to get the data of a mesh and then use any rendering library that accepts numpy arrays.
In the next release of pymeshlab there will be a function that does this automatically using [polyscope](https://polyscope.run/py/).

**Comment by LeoXiaoNian** [comment]
thanks a lot!  Mr.Alessandro, Do you mean that the next version will have its own visualization function? When can it be out? Can you disclose it in advance?  ：）

**Comment by alemuntoni** [comment]
Yes, there will be a function that allows to render all the meshes of the meshset.
I cannot release it in advance because it is not ready yet. We will release a new version when there will be a sufficient number of new features in the library.
You can try the [nighty builds](https://github.com/cnr-isti-vclab/PyMeshLab/wiki/How-to-intall-the-last-nightly) at your own risk.
You'll have to first install `polyscope`, and then you will be able to use the new functionality.
The new method can be called with:
```
ms = pymeshlab.MeshSet()
# load and do some computations with meshes
ms.show_polyscope()
```
