### ISSUE TITLE
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found 

### ISSUE THREAD

**Issue by liwenssss** [cnr-isti-vclab/PyMeshLab#246]
hello, I installed pymeshlab via pip and when I import pymeshlab, I got the error '/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found '. How can I solve it ?

**Comment by MikoSamey** [comment]
Maybe your GLIBC version is lower than 2.25.
You can check the version with this command `ldd --version`;

I solved the problem by lowering the version of pymeshlab：
`pip install pymeshlab==0.2.1`
I also tried to upgrade the version of GLIBC, but it 's complicated and I failed.Because it's an important API of system.

**Comment by liwenssss** [comment]
> Maybe your GLIBC version is lower than 2.25. You can check the version with this command `ldd --version`;
> 
> I solved the problem by lowering the version of pymeshlab： `pip install pymeshlab==0.2.1` I also tried to upgrade the version of GLIBC, but it 's complicated and I failed.Because it's an important API of system.

Thanks bro,  it works for me !

**Comment by alemuntoni** [comment]
See #157.
