### ISSUE TITLE
generate_surface_reconstruction_screened_poisson filter is very slow

### ISSUE THREAD

**Issue by sizekick-manu** [cnr-isti-vclab/PyMeshLab#283]
My system has more than 30 cores. Whenever I am running a script that uses the `generate_surface_reconstruction_screened_poisson` method, unless I assign all the CPUs to the script, it is insanely slow. I time checked my code and could not find any that was taking as much time as this method. Why does this method need all the CPU cores for execution? And how can I speed up my script. I tried using concurrent futures for my script but for some reason it slows down `generate_surface_reconstruction_screened_poisson` even more.

**Comment by alemuntoni** [comment]
please refer to the [original repository](https://github.com/mkazhdan/PoissonRecon) of the Screened Poisson Surface Reconstruction and the relative paper to understand what is going on. You can play with the parameters to speedup the process (with different results in the output). 
If you notice different execution times between meshlab and pymeshlab, or between the original source code, please let me know.
Otherwise, this is not a pymeshlab issue.
