### ISSUE TITLE
generate_surface_reconstruction_vcg is using tempory files but I can't specify where to put them

### ISSUE THREAD

**Issue by Nosenzor** [cnr-isti-vclab/PyMeshLab#317]
Hi I'm using pymeshlab within a docker with strict read/write permission.

When running `generate_surface_reconstruction_vcg` there's two messages  that indicates files are used within the function:
* `Trying to import a non-ply file __TMP.`
* `Mesh Saved 'plymcout.ply`

When I'm using it I observe that some file seems to be used as intermediate representation but I can't specify the temp directory where it can store those files.
Then the function fail...although i'm not sure it is related to the file right issue.

How can i set the directory where to store temporaries ?

**Comment by SeeSpineNedim** [comment]
I am having the exact same issue as well. Would love to get some further insight on this. What I have is working fine locally but fails with these errors when containerized and deployed in a cloud environment

**Comment by alemuntoni** [comment]
Just solved this issue. The filter was set to save temporary files in the current directory. Changed it in order to save in the `tmp` directory. 
You can try it by [downloading and installing](https://github.com/cnr-isti-vclab/PyMeshLab/wiki/How-to-install-the-last-nightly-version) the last wheel from the devel branch (when it will be ready).
Let me know if it works.
