### ISSUE TITLE
Can't access compute_geometric_measures results from a Python script

### ISSUE THREAD

**Issue by riosnav** [cnr-isti-vclab/PyMeshLab#39]
According to the [documentation](https://pymeshlab.readthedocs.io/en/latest/filter_list.html#compute_geometric_measures), I should "Open the layer dialog to see the results.", but as I understand this is part of MeshLab's GUI as in other section of the documentation it is said to click on it.

Am I missing something? Is there a way to access those results from a Python script?

Thank you.

**Comment by alemuntoni** [comment]
Thanks for reporting this. 
Filters documentation has been written when there was just the GUI, and therefore needs to be updated.
And also this filter needs to be updated, since right now it does not return anything.
I'll solve this issue in the next version of pymeshlab. You will be able to do:
```
measures = ms.apply_filter('compute_geometric_measures')
```
where measures is a dictionary that maps keyword strings to different kind of values.

**Comment by alemuntoni** [comment]
Update: in the next version (available soon), almost all the filters inside Filter Measure will return values in the output dictionary returned by the `apply_filter` function.

However, some values that should be represented with vectors or matrices are going to be missing because they require additional software refactoring in meshlab.

**Comment by alemuntoni** [comment]
I can confirm that the filter will output all the values in the output dictionary in the next pymeshlab release!

**Comment by alemuntoni** [comment]
Solved with version 0.1.9!

**Comment by FerbyCremer** [comment]
FYI, if anyone is still looking at this, and/or someone can update the documentation: you need to use` 'get_geometric_measures' `
that seems to be the pattern for filters now, using `'get'` instead of `'compute'`
