### ISSUE TITLE
ambient occlusion segmentation fault

### ISSUE THREAD

**Issue by nitschkematthew** [cnr-isti-vclab/PyMeshLab#43]
Running PyMeshLab on Windows Subsystem for Linux. Had some initial problems with dependencies (see here https://github.com/cnr-isti-vclab/PyMeshLab/issues/41#issue-779957211) but now successfully installed and passes all 18 pytests.

However I am running into some troubles with the ambient occlusion filter with one of the testing meshes (cow.obj) that throws a segfault
```
PyMeshLab 0.1.7 based on MeshLab 2020.12d
>>> ms = ml.MeshSet()
>>> ms.load_new_mesh('cow.obj')
>>> ms.apply_filter('ambient_occlusion')
----------AngleRad 0.523599 Angledeg 30.000000 ratio 0.066987 vn 128 vn2 1910
asked 1910 got 1910 (expecting 127 instead of 128)
Segmentation fault (core dumped)
```
Are there any more dependencies that this filter relies upon that I may be missing?
Thanks!

**Comment by alemuntoni** [comment]
Thanks for reporting, I replicated the issue on linux, therefore it is not related with the windows subsystem for linux. I'll investigate on this.

**Comment by Crofttime** [comment]
I can't get ambient occlusion to work on Windows either, also 'volumetric_obscurance' doesn't seem to work either - it just quits without error or exporting the mesh.

BTW, PyMeshLab is the best thing ever, thanks so much for your work on it!

**Comment by alemuntoni** [comment]
Update:
with 0.1.8 `ambient_occlusion`, `volumetric_obscurance` and some other filters will still crash. I am writing here some technical details on why this still happens and why it will take some time to be fixed (if someone is interested on technicalities :D).

Some filters in meshlab require an active OpenGL context, and right now this context cannot be activated in pymeshlab.
MeshLabServer used to always activate this context, and this led to issues on OpenGL dependency also when it was not required (see https://github.com/cnr-isti-vclab/meshlab/issues/78). 

Right now, I added some software infrastructure that should activate the context ONLY when running a filter that needs it.
However, this still needs to be properly tested because first another dependency needs to be removed. In fact, these filters also require an active QApplication. This dependency is very painful to get rid off, and I still don't know if it can be removed.

I'll write more updates whenever I'll find a way to bypass all these issues!

**Comment by alemuntoni** [comment]
Ambient occlusion should work fine in the next pymeshlab version!

**Comment by smoothumut** [comment]
I am having the same problem, I have installed pymeshlab 0.2 and newer versions but it keeps stopping without giving any problem.

for mesh_fp in tqdm(list(mesh_folder.glob('*.ply'))):
    remesh_fp = remesh_folder / mesh_fp.name
    ms = pymeshlab.MeshSet()
    ms.load_new_mesh(str(mesh_fp.absolute()))
    ms.repair_non_manifold_edges_by_removing_faces()
    ms.subdivision_surfaces_midpoint(iterations=10, threshold=pymeshlab.Percentage(args.remesh_percentage))
    ms.ambient_occlusion(occmode='per-Face (deprecated)', reqviews=256)
    face_quality_array = ms.current_mesh().face_quality_array()

code gets stuck on ambient_occlusion function
you can find 2 different meshes that I have tried and both have the same problem
[mesh_folder.zip](https://github.com/cnr-isti-vclab/PyMeshLab/files/9556805/mesh_folder.zip)

I hope you can help me on this, this is very critical for developing our deep learning model.
thanks in advance

**Comment by ganovelli** [comment]
Wqqàà AA

Il mar 13 set 2022, 14:03 smoothumut ***@***.***> ha scritto:
