### ISSUE TITLE
normals error

### ISSUE THREAD

**Issue by marcomusy** [cnr-isti-vclab/PyMeshLab#72]
When manually creating a `Mesh` with normals I get now thid error dump in v0.2 but not in v0.18.5:
```
PyMeshLab 0.2 based on MeshLab 2020.12d
using cached file: /tmp/bunny.obj
(2503, 3) (2503, 3)
Traceback (most recent call last):
  File "examples/other/pymeshlab1.py", line 18, in <module>
    print("Can convert back to pymeshlab.MeshSet:\n\t", vedo_mesh.to_meshlab())
  File "/home/musy/dolfx/vedo/vedo/pointcloud.py", line 3240, in to_meshlab
    return utils.vedo2meshlab(self)
  File "/home/musy/dolfx/vedo/vedo/utils.py", line 1554, in vedo2meshlab
    v_normals_matrix=vmesh.normals(cells=False, compute=False),
pymeshlab.pmeshlab.PyMeshLabException: Error while creating mesh: the number of vertex normals is different from the number of vertices.
```
where indeed the number is the same.

Also has `MeshLab.print_filter_parameter_list()` changed name?

**Comment by alemuntoni** [comment]
I don't see any error on these lines:
https://github.com/cnr-isti-vclab/PyMeshLab/blob/0722b057c4e4cc759495bd24e1b297c18d9627cd/src/pymeshlab/pymeshlab/mesh.cpp#L75-L81

please check that the number of **rows** of the numpy array of the normals is the same as the number of faces.
Also note that this check has been introduced in this version. The previous version was accepting also wrong arrays.
If the issue persist, please share the script you are running in order to check what's happening.

> Also has `MeshLab.print_filter_parameter_list()` changed name?

some methods regarding listing filters and filter parameters have been moved as module functions, and you can call them in this way:
```
pymeshlab.print_filter_parameter_list(`some_filter`)
```
https://pymeshlab.readthedocs.io/en/latest/classes/pmeshlab.html

**Comment by marcomusy** [comment]
maybe in line 45 you should have `vertexNormals.rows()` instead of  `vertexNormals.size()`?

**Comment by alemuntoni** [comment]
Oh yes, thank you! 
I read faces instead of vertices in your first post, sorry! I'll fix this ASAP!
Thanks again!

**Comment by marcomusy** [comment]
thanks for writing this great library - it's so straightforward to [interface](https://github.com/marcomusy/vedo/blob/master/examples/other/pymeshlab1.py) to `vedo` and it provides such an amazing set of functionalities!

**Comment by alemuntoni** [comment]
Thanks :)
I fixed the issue (I was a bit tired yesterday, sorry again!)
I am re-releasing version 0.2, in a few hours I'll update also the pypi package and with a forced upgrade should work fine :)
