### ISSUE TITLE
'parameterization__texturing_from_registered_rasters' generates black texture

### ISSUE THREAD

**Issue by ramazanabd** [cnr-isti-vclab/PyMeshLab#76]
Thanks for resolving #54 , but now after applying 'parameterization__texturing_from_registered_rasters', output texture file is either all black or erroneous + very dark. 
The first two files are the output of pymeshlab and the third is the correct file when the standalone meshlab is used.

The code I'm using is smth like this:
ms = ml.MeshSet()

ms.load_new_mesh('stairs_dense.0.ply')
ms.load_new_raster('1.jpg')
ms.load_new_raster('2.jpg')
ms.load_new_raster('3.jpg')
ms.load_new_raster('4.jpg')
ms.load_new_raster('5.jpg')
ms.load_new_raster('6.jpg')
ms.apply_filter('import_cameras_for_active_rasters_from_file', importfile = 'cameras.out')
ms.apply_filter('compute_normals_for_point_sets')
ms.apply_filter('surface_reconstruction_screened_poisson')
ms.apply_filter('parameterization__texturing_from_registered_rasters', texturesize = 1024, texturename = 'test.png')

 
![test_erroneous](https://user-images.githubusercontent.com/41662146/109643573-c1679000-7b97-11eb-85e4-35f422e88f2e.png)
![test_black](https://user-images.githubusercontent.com/41662146/109643623-d512f680-7b97-11eb-98f4-7a76de31a7c2.png)
![stairs_texture](https://user-images.githubusercontent.com/41662146/109643656-e1974f00-7b97-11eb-81f3-07b7176bbb59.png)

**Comment by alemuntoni** [comment]
Could you please share also the input model and the rasters?

**Comment by ramazanabd** [comment]
I attached the rasters, model and cameras.out

[stairs_demo.zip](https://github.com/cnr-isti-vclab/PyMeshLab/files/6073144/stairs_demo.zip)

**Comment by MLucient** [comment]
Hi @alemuntoni - like many other folks, I want to join in appreciating PyMeshLab - it's a huge win for those of us trying to make ambitious reconstruction pipelines!

But also, I do want to +1 this issue; my team just started trying to port some things to PyMeshLab and we've been unable to fix this issue on our side so far. One suggestion/idea? I know that standalone Meshlab sometimes has some implicit rules about pathing/etc with respect to where it expects images/rasters to be, and I've seen a version of this issue (black/null texture) with this particular filter fixed by simply putting every resource in a single directory before doing any of the operations in MeshLab, so I wonder if something similar is happening here?

Also, if there's anything you'd like me to help test, I'd be happy to help out as well, just let me know!

**Comment by alemuntoni** [comment]
I am sorry that the fix of this is taking a long time, but I still didn't have time to investigate. I'll try to check this as soon as possible, but right now I am pushing for a new meshlab release.. I'll write here whenever I'll have some news.

About what is causing this trouble, I don't think that it is related to relative/absolute paths of textures... I already fixed that issue in a previous commit. I think that this is still related to the GL context, that is required by the `parameterization__texturing_from_registered_rasters` filter...

**Comment by alemuntoni** [comment]
This issue should be fixed with the last commit. The issue was actually related to the double precision of meshlab (2020.12d was producing black textures), and was affecting both `import_cameras_for_active_rasters_from_file` and `parameterization__texturing_from_registered_rasters`.

@ramazanabd @MLucient if you want to try the nightly that fixes this, you can download the artifact package produced by [github actions](https://github.com/cnr-isti-vclab/PyMeshLab/actions) (select the right one depending on your platform and your python version)  and extract the content of the zip file in a directory called `pymeshlab`. Then, from outside that folder, use pymeshlab like you normally do. If you could try  and check if it works fine also for you, it would be really appreciated!!

Note: as stated in #51, the output of `compute_normals_for_point_sets` in 2020.12d is different from the one computed with meshlab 2020.12.

**Comment by ramazanabd** [comment]
It works for me as well. Thanks for the fix!

**Comment by MLucient** [comment]
Yep, works for me too. Thanks @alemuntoni !
